### ISSUE TITLE
In geocoding when the api status code is OVER_QUERY_LIMIT, we should raise an exception instead of retrying

### ISSUE THREAD

**Issue by bmamouri** [googlemaps/google-maps-services-python#130]
When Google Maps API responses with `OVER_QUERY_LIMIT` status code, we should raise an exception instead of retrying. According to the API docs, `OVER_QUERY_LIMIT` is an indicator that the user is out of quota. This quota is set on API manager and is on daily basis.

This is the relevant code from `client.py` file:
```
    def _get(self, url, params, first_request_time=None, retry_counter=0,
             base_url=_DEFAULT_BASE_URL, accepts_clientid=True,
             extract_body=None, requests_kwargs=None):
        ....
        try:
            if extract_body:
                result = extract_body(resp)
            else:
                result = self._get_body(resp)
            self.sent_times.append(time.time())
            return result
        except googlemaps.exceptions._RetriableRequest:
            # Retry request.
            return self._get(url, params, first_request_time, retry_counter + 1,
                             base_url, accepts_clientid, extract_body)

    def _get_body(self, resp):
        ....
        if api_status == "OVER_QUERY_LIMIT":
            raise googlemaps.exceptions._RetriableRequest()
```

What is happening here is that when API responses with `OVER_QUERY_LIMIT`, we repeat the request until we raise `googlemaps.exceptions.Timeout` exception. This exception is misguiding as the real reason for failing in receiving the data is lack of quota not HTTP timeout.

I think we need to use one of the following solutions:
- If the API response code is `OVER_QUERY_LIMIT` we should just raise an appropriate exception straight away. No need to retrying.
- Or alternatively we can retry until we exahust the `retry_counter` and eventually raise an appopriate exception.

**Comment by rbouchez** [comment]
Thing is, the OVER_QUERY_ERROR is also raised when exceeding the short term quota (for example free customers have a short term quota of 10 queries per second, https://developers.google.com/maps/documentation/geocoding/usage-limits).

It is actually a bit more complicated than that, because some short term quotas might for example allow 20 queries per 2 seconds (to handle short bursts): in that case, if the users send 20 queries simultaneously just after the short term reset, they might get OVER_QUERY_LIMIT even after waiting one full second after the first request. I believed that's one of the reasons for the retry.

**Comment by stephenmcd** [comment]
Duplicate #109
