### ISSUE TITLE
The most outside brace '['  is superfluous?

### ISSUE THREAD

**Issue by tengpeng** [googlemaps/google-maps-services-python#157]
Python client:

```
gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')
----->[<-------{u'address_components': [{u'long_name': u'1600',
        Here  
```

Official API:

```
{
   "results" : [
```

Is this brace superfluous?

The consequence: when we parse the json file, we had to add `[0]` to unwrap the `[]`

**Comment by stephenmcd** [comment]
This isn't an issue with the Python client, since the client merely returns whatever the geocoding web service does. Nonetheless, here's the relevant explanation from the [geocoding docs](https://developers.google.com/maps/documentation/geocoding/intro#GeocodingResponses):

_Generally, only one entry in the "results" array is returned for address lookups, though the geocoder may return several results when address queries are ambiguous._
