### ISSUE TITLE
Google Maps 

### ISSUE THREAD

**Issue by PythonicCoder101** [googlemaps/google-maps-services-python#173]
I did this but how do you add both Directional and Geocoding API's in the example shown on other page???

**Comment by PythonicCoder101** [comment]
Also when I run it, keeps giving me a 404 error code shown below:

raise googlemaps.exceptions.HTTPError(response.status_code)
googlemaps.exceptions.HTTPError: HTTP Error: 400

**Comment by stephenmcd** [comment]
Can you show some example code showing what you're trying to do?

**Comment by PythonicCoder101** [comment]
import googlemaps
from datetime import datetime



gmaps = googlemaps.Client(key='API Key')

geocode_result = gmaps.geocode('Adress')

reverse_geocode_result = gmaps.reverse_geocode(location))

now = datetime.now()

directions_result = gmaps.directions('Los Angeles, CA',  '1600 Pennsylvania Ave NW, Washington, DC ', mode='car', departure_time=now)

**Comment by stephenmcd** [comment]
What is the `location` variable?

**Comment by PythonicCoder101** [comment]
Location is not a variable just a placeholder for real location for which I have not included for privacy reasons.

**Comment by stephenmcd** [comment]
Well whatever you're using as the value there is what's causing the error. It should be a latitude/longitude, as a string or sequence. 

Also in your directions query, "car" isn't a value value for the "mode" argument - you can see the valid values here: https://developers.google.com/maps/documentation/directions/intro#traffic-model

I'll close this for now since you should be able to resolve this on your own.
