### ISSUE TITLE
Handling Exceed API quota exception

### ISSUE THREAD

**Issue by capiscuas** [googlemaps/google-maps-services-python#220]
Hi, I realized that the library keeps repeating the request if receives
{'status': 'OVER_QUERY_LIMIT', 'error_message': 'You have exceeded your daily request quota for this API.', 'html_attributions': [], 'results': []}

json responses and therefore repeatingly trying over and over.
Could you raise googlemaps.exceptions._RetriableRequest exceptions out?

Thanks a lot.

**Comment by Alexndrrr** [comment]
You can change that behavior by setting the retry_over_query_limit flag when constructing the Client, like this:
`client = maps.Client(key=API_KEY, queries_per_second=50, retry_over_query_limit=False)`


If you do that, the client will raise the exception `googlemaps.exceptions._OverQueryLimit` when it hits the limit instead of retrying over and over.

**Comment by rarogers** [comment]
@Alexndrrr - this doesn't work. Throws a TypeError. I looked at the arguments for Client() and retry_over_query_limit is not included.

`import inspect
import googlemaps
inspect.getfullargspec(googlemaps.Client)`

> FullArgSpec(args=['self', 'key', 'client_id', 'client_secret', 'timeout', 'connect_timeout', 'read_timeout', 'retry_timeout', 'requests_kwargs', 'queries_per_second', 'channel'], varargs=None, varkw=None, defaults=(None, None, None, None, None, None, 60, None, 10, None), kwonlyargs=[], kwonlydefaults=None, annotations={})

>

**Comment by nifred** [comment]
Still a problem with the version 2.5.1 install by pip.
The client code is not the same as this github repository.
So, if you want to manage your quota limit you have to change it by yourself.
Cause it is look like that this problem still remaining since 2016: the API will send retry request no matter of your quota limit :D !

**Comment by jpoehnelt** [comment]
The addition of `retry_over_query_limit` was included in the 3.0.0 release. Sorry about the lack of a changelog for those releases.

**Comment by cosmith** [comment]
This should probably be the default... but I'm still glad we have it as an option
