### ISSUE TITLE
find_place only returns a single non-cover photo?

### ISSUE THREAD

**Issue by joshuakoh7** [googlemaps/google-maps-services-python#349]
Hello,

Is there a reason why using find_place and requesting the photos field returns only a single photo under the photos array? I can live with a single photo but it's not even the main photo they use when you look up the place with the Google Maps app!

place_id for reference: ChIJMxZ-kwQZ2jERdsqftXeWCWI

Is there anything I'm doing wrong?

Thanks!

**Comment by jpoehnelt** [comment]
Hi @joshuakoh7,

I don't think you are doing anything wrong! I found this in the documentation.

>Find Place, Nearby Search, and Text Search requests also return a single photo reference per place, when relevant. https://developers.google.com/places/web-service/photos

I suggest filing a feedback request here: https://issuetracker.google.com/issues/new?component=188872&template=789309

Alternatively, you can make an additional request to retrieve additional photos: https://developers.google.com/places/web-service/photos

I am going to close this issue here as there is no action to take for this library. Sorry I don't have a better answer!
